[package]
name = "snow-shot-ocr"
version = "0.1.0"
edition = "2024"
publish = false
workspace = "../../src-tauri"

[dependencies]
image = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true, features = ["fs", "rt", "macros"] }
rayon = { workspace = true }

num_cpus = "1.17.0"
ort = { version = "2.0.0-rc.10", default-features = false }
paddle-ocr-rs = "0.6.0"
