import { SnowTheme } from "../theme/snow-theme.slint";

export component ColorMagnifier inherits Rectangle {
    in property <image> source;
    in property <string> label;
    in property <int> format-index;

    width: 184px;
    height: 230px;
    border-radius: SnowTheme.radius-sm;
    border-width: 1px;
    border-color: #ffffff68;
    background: #202327f2;
    drop-shadow-color: #00000066;
    drop-shadow-blur: 14px;
    drop-shadow-offset-y: 4px;

    Image {
        x: 7px;
        y: 7px;
        width: 170px;
        height: 170px;
        source: root.source;
        image-fit: fill;
        image-rendering: pixelated;
    }
    Rectangle {
        x: 7px + 80px;
        y: 7px + 80px;
        width: 10px;
        height: 10px;
        border-width: 2px;
        border-color: #ffffff;
        background: transparent;
    }
    Rectangle {
        x: 7px + 79px;
        y: 7px + 79px;
        width: 12px;
        height: 12px;
        border-width: 1px;
        border-color: #000000;
        background: transparent;
    }
    Text {
        x: 7px;
        y: 181px;
        width: 170px;
        height: 42px;
        text: root.label;
        color: #f3f5f7;
        font-size: 10px;
        horizontal-alignment: center;
        vertical-alignment: center;
        wrap: word-wrap;
    }
}
