export component SelectionEdgeHandle inherits Rectangle {
    in property <MouseCursor> cursor: ns-resize;
    callback drag-started(float, float);
    callback drag-moved(float, float, bool, bool);

    private property <bool> dragging: false;

    background: transparent;

    handle-area := TouchArea {
        mouse-cursor: root.cursor;

        pointer-event(event) => {
            if (event.kind == PointerEventKind.down && event.button == PointerEventButton.left) {
                root.dragging = true;
                root.drag-started(self.mouse-x / 1px, self.mouse-y / 1px);
            }

            if (event.kind == PointerEventKind.move && root.dragging) {
                root.drag-moved(
                    self.mouse-x / 1px,
                    self.mouse-y / 1px,
                    event.modifiers.shift,
                    event.modifiers.control,
                );
            }

            if (event.kind == PointerEventKind.up || event.kind == PointerEventKind.cancel) {
                root.dragging = false;
            }
        }
    }
}
