[package]
name = "snow-shot-clipboard"
version = "0.1.0"
edition = "2024"
publish = false
workspace = "../../src-tauri"

[dependencies]
image = { workspace = true }
rayon = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
clipboard-win = { workspace = true }

[dev-dependencies]
snow-shot-capture = { workspace = true }
